const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');
const { log } = require('./logger');

const AGENT_ID = 'googleads';
const SCRIPT_FILE = path.join(__dirname, '../../data/google-ads-script.js');
const COPY_FILE   = path.join(__dirname, '../../data/google-ads-copy.json');

async function callClaude(prompt) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not set');
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01', 'content-type': 'application/json' },
    body: JSON.stringify({ model: 'claude-haiku-4-5-20251001', max_tokens: 1500,
      messages: [{ role: 'user', content: prompt }] }),
  });
  if (!res.ok) throw new Error(`Claude API ${res.status}`);
  return (await res.json()).content[0].text.trim();
}

async function run() {
  log(AGENT_ID, 'info', 'Google Ads agent starting — generating campaign scripts & copy…');
  const copy = {};

  try {
    // 1. Generate ad copy for each product category
    const categories = [
      { id: 'tshirts',  name: 'Custom T-Shirts' },
      { id: 'hoodies',  name: 'Custom Hoodies' },
      { id: 'glasses',  name: 'Custom Sunglasses' },
      { id: 'mugs',     name: 'Custom Mugs' },
      { id: 'caps',     name: 'Custom Caps' },
      { id: 'tote',     name: 'Custom Tote Bags' },
    ];

    for (const cat of categories) {
      const raw = await callClaude(
        `Generate Google Ads responsive search ad copy for "${cat.name}" sold on WEARIT (custom print-on-demand store).
Return ONLY valid JSON in this exact format:
{
  "headlines": ["headline1","headline2","headline3","headline4","headline5"],
  "descriptions": ["desc1","desc2","desc3"]
}
Rules: headlines max 30 chars each. Descriptions max 90 chars each. Focus on: custom, personalized, fast shipping, quality, your design. No emoji. No exclamation more than once.`
      );
      try {
        const jsonStart = raw.indexOf('{');
        const jsonEnd = raw.lastIndexOf('}') + 1;
        copy[cat.id] = JSON.parse(raw.slice(jsonStart, jsonEnd));
        log(AGENT_ID, 'success', `Ad copy generated: ${cat.name}`);
      } catch {
        copy[cat.id] = { headlines: [`Custom ${cat.name}`, 'Design Your Own', 'Ships in 48 Hours', 'No Minimums', 'Premium Quality'], descriptions: [`Create your own ${cat.name.toLowerCase()} with WEARIT. Upload your design, we handle the rest.`, 'Print on demand with no minimums. Free worldwide shipping on orders over $50.', 'Your design printed on premium products. 30-day quality guarantee.'] };
        log(AGENT_ID, 'warn', `Used fallback copy for ${cat.name}`);
      }
    }

    fs.writeFileSync(COPY_FILE, JSON.stringify({ generated: new Date().toISOString(), categories: copy }, null, 2));
    log(AGENT_ID, 'success', 'Ad copy saved to data/google-ads-copy.json');

    // 2. Generate the Google Ads Script
    const headlines = Object.entries(copy).map(([id, c]) =>
      `  // ${id}\n  ${c.headlines.map(h => `'${h.replace(/'/g, "\\'")}'`).join(', ')}`
    ).join(',\n');

    const script = `/**
 * WEARIT — Google Ads Script
 * Auto-generated by WEARIT Ad Agent on ${new Date().toLocaleDateString()}
 *
 * HOW TO USE:
 * 1. Go to your Google Ads account
 * 2. Click Tools & Settings → Scripts
 * 3. Click + (New Script)
 * 4. Paste this entire file
 * 5. Click Preview, then Save and Run
 *
 * This script creates search campaigns for your top product categories.
 * Re-paste the updated version from /admin.html every time it regenerates.
 */

var CAMPAIGN_NAME = 'WEARIT — Custom Products';
var DAILY_BUDGET_USD = 20;
var FINAL_URL = 'https://wearit.com/editor.html';

var PRODUCT_GROUPS = [
  {
    name: 'Custom T-Shirts',
    keywords: ['custom t-shirts', 'personalized t-shirts', 'print on demand shirts', 'design your own t-shirt', 'custom tee printing'],
    headlines: ${JSON.stringify(copy.tshirts?.headlines || ['Custom T-Shirts', 'Design Your Own Tee', 'Ships in 48 Hours', 'No Minimums', 'Premium Quality Print'])},
    descriptions: ${JSON.stringify(copy.tshirts?.descriptions || ['Create custom t-shirts with your design. Premium quality, fast shipping worldwide.', 'Upload your artwork and get custom printed t-shirts. No minimum order quantity.'])}
  },
  {
    name: 'Custom Hoodies',
    keywords: ['custom hoodies', 'personalized hoodies', 'print on demand hoodies', 'design your own hoodie'],
    headlines: ${JSON.stringify(copy.hoodies?.headlines || ['Custom Hoodies', 'Design Your Hoodie', 'Premium Print Quality', 'Fast Worldwide Ship', 'No Minimums'])},
    descriptions: ${JSON.stringify(copy.hoodies?.descriptions || ['Design custom hoodies with your logo or artwork. Premium quality, ships in 48 hours.', 'Print on demand hoodies with no minimum orders. Your design, your brand.'])}
  },
  {
    name: 'Custom Sunglasses',
    keywords: ['custom sunglasses', 'personalized glasses', 'custom eyewear', 'branded sunglasses'],
    headlines: ${JSON.stringify(copy.glasses?.headlines || ['Custom Sunglasses', 'Your Logo On Shades', 'UV400 Protection', 'Ships Worldwide', 'Stand Out'])},
    descriptions: ${JSON.stringify(copy.glasses?.descriptions || ['Custom printed sunglasses with UV400 protection. Add your logo or artwork to premium frames.', 'Personalized eyewear for brands, events, and individuals. No minimum order.'])}
  },
  {
    name: 'Custom Mugs',
    keywords: ['custom mugs', 'personalized mugs', 'photo mugs', 'custom coffee mug', 'branded mugs'],
    headlines: ${JSON.stringify(copy.mugs?.headlines || ['Custom Mugs', 'Personalized Gifts', 'Full Wrap Print', 'Dishwasher Safe', 'Ships in 48 Hours'])},
    descriptions: ${JSON.stringify(copy.mugs?.descriptions || ['Custom printed mugs, perfect for gifts or branding. Full wrap print, dishwasher safe.', 'Design your own mug with photos, logos, or artwork. From $14.99. Ships worldwide.'])}
  },
];

function main() {
  Logger.log('WEARIT Google Ads Script starting…');
  var campaign = getOrCreateCampaign();
  Logger.log('Campaign: ' + campaign.getName());

  PRODUCT_GROUPS.forEach(function(group) {
    var adGroup = getOrCreateAdGroup(campaign, group.name);
    addKeywords(adGroup, group.keywords);
    addResponsiveSearchAd(adGroup, group.headlines, group.descriptions);
    Logger.log('Processed ad group: ' + group.name);
  });

  Logger.log('WEARIT script complete. Check your campaigns dashboard.');
}

function getOrCreateCampaign() {
  var iter = AdsApp.campaigns().withCondition('Name = "' + CAMPAIGN_NAME + '"').get();
  if (iter.hasNext()) return iter.next();

  var op = AdsApp.newCampaignBuilder()
    .withName(CAMPAIGN_NAME)
    .withStatus('PAUSED')
    .withBudget(DAILY_BUDGET_USD)
    .withBiddingStrategy('TARGET_CPA')
    .build();

  var campaign = op.getResult();
  Logger.log('Created new campaign: ' + CAMPAIGN_NAME + ' (status: PAUSED — review before enabling)');
  return campaign;
}

function getOrCreateAdGroup(campaign, name) {
  var iter = campaign.adGroups().withCondition('Name = "' + name + '"').get();
  if (iter.hasNext()) return iter.next();

  var op = campaign.newAdGroupBuilder()
    .withName(name)
    .withStatus('ENABLED')
    .withCpc(1.5)
    .build();

  return op.getResult();
}

function addKeywords(adGroup, keywords) {
  keywords.forEach(function(kw) {
    try {
      adGroup.newKeywordBuilder().withText(kw).withMatchType('PHRASE').build();
      adGroup.newKeywordBuilder().withText('[' + kw + ']').withMatchType('EXACT').build();
    } catch(e) { Logger.log('Keyword already exists or error: ' + kw); }
  });
}

function addResponsiveSearchAd(adGroup, headlines, descriptions) {
  try {
    adGroup.newAd().responsiveSearchAdBuilder()
      .withHeadlines(headlines.map(function(h) { return { text: h }; }))
      .withDescriptions(descriptions.map(function(d) { return { text: d }; }))
      .withFinalUrl(FINAL_URL)
      .build();
  } catch(e) { Logger.log('Ad may already exist: ' + e.message); }
}
`;

    fs.writeFileSync(SCRIPT_FILE, script);
    log(AGENT_ID, 'success', 'Google Ads script saved to data/google-ads-script.js — paste into Google Ads → Tools → Scripts');
    log(AGENT_ID, 'success', 'Google Ads agent run complete.');
  } catch (err) {
    log(AGENT_ID, 'error', `Google Ads agent error: ${err.message}`);
  }
}

module.exports = { run, AGENT_ID };
