-- =============================================================================
-- CALLA Agent System Schema
-- Agent tables for the AI Marketing Manager and sub-agents
-- =============================================================================

-- ---------------------------------------------------------------------------
-- weekly_plans
-- Stores the master weekly marketing plan generated by the Marketing Manager.
-- One active plan per week. plan_json holds the full WeeklyPlan object.
-- ---------------------------------------------------------------------------
create table if not exists weekly_plans (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  week_of     date not null,
  goal        text,
  plan_json   jsonb,
  status      text not null default 'active'
    check (status in ('active', 'archived', 'superseded'))
);

-- Only one active plan at a time
create unique index if not exists weekly_plans_active_unique
  on weekly_plans (status)
  where status = 'active';

-- Fast lookup of latest plan
create index if not exists weekly_plans_created_at_idx
  on weekly_plans (created_at desc);

comment on table weekly_plans is
  'Weekly marketing plans generated by the AI Marketing Manager every Monday.';


-- ---------------------------------------------------------------------------
-- content_posts
-- Blog posts + all social media versions generated by the Content Agent.
-- status: ready → published | archived
-- ---------------------------------------------------------------------------
create table if not exists content_posts (
  id                  uuid primary key default gen_random_uuid(),
  created_at          timestamptz not null default now(),
  topic               text,
  blog_post           text,
  instagram_caption   text,
  twitter_thread      jsonb,       -- { tweets: string[] }
  linkedin_post       text,
  meta_title          text,        -- SEO, under 60 chars
  meta_description    text,        -- SEO, under 160 chars
  status              text not null default 'ready'
    check (status in ('ready', 'published', 'archived')),
  published_at        timestamptz
);

create index if not exists content_posts_status_idx
  on content_posts (status);

create index if not exists content_posts_created_at_idx
  on content_posts (created_at desc);

comment on table content_posts is
  'AI-generated content posts with all format variants. Created by the Content Agent.';


-- ---------------------------------------------------------------------------
-- seo_reports
-- Weekly SEO analysis and recommendations generated by the SEO Agent.
-- ---------------------------------------------------------------------------
create table if not exists seo_reports (
  id                  uuid primary key default gen_random_uuid(),
  created_at          timestamptz not null default now(),
  target_page         text not null,
  keywords            jsonb,       -- KeywordEntry[]
  meta_title          text,
  meta_description    text,
  content_gaps        jsonb,       -- string[]
  backlink_targets    jsonb,       -- BacklinkTarget[]
  status              text not null default 'new'
    check (status in ('new', 'reviewed', 'implemented', 'archived'))
);

create index if not exists seo_reports_target_page_idx
  on seo_reports (target_page);

create index if not exists seo_reports_created_at_idx
  on seo_reports (created_at desc);

comment on table seo_reports is
  'SEO analysis reports generated by the AI SEO Expert every Monday.';


-- ---------------------------------------------------------------------------
-- prospects
-- Businesses identified as potential CALLA customers.
-- The Outreach Agent reads from this table and marks prospects as contacted.
-- ---------------------------------------------------------------------------
create table if not exists prospects (
  id                uuid primary key default gen_random_uuid(),
  created_at        timestamptz not null default now(),
  business_name     text,
  business_type     text,
  instagram_handle  text,
  email             text,
  city              text,
  status            text not null default 'new'
    check (status in ('new', 'contacted', 'responded', 'converted', 'disqualified'))
);

create index if not exists prospects_status_idx
  on prospects (status);

create index if not exists prospects_business_type_idx
  on prospects (business_type);

-- Prevent duplicate outreach to the same Instagram handle
create unique index if not exists prospects_instagram_unique
  on prospects (instagram_handle)
  where instagram_handle is not null;

comment on table prospects is
  'Potential CALLA customers. Managed by the AI Outreach Agent.';


-- ---------------------------------------------------------------------------
-- outreach_queue
-- Personalized cold DMs and emails generated by the Outreach Agent.
-- status: ready → sent | failed | skipped
-- ---------------------------------------------------------------------------
create table if not exists outreach_queue (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz not null default now(),
  prospect_id     uuid not null references prospects (id) on delete cascade,
  dm_copy         text,           -- Instagram DM, max 5 lines
  email_subject   text,
  email_body      text,           -- ~100 words
  channel         text not null default 'instagram'
    check (channel in ('instagram', 'email', 'both')),
  status          text not null default 'ready'
    check (status in ('ready', 'sent', 'failed', 'skipped')),
  sent_at         timestamptz
);

create index if not exists outreach_queue_status_idx
  on outreach_queue (status);

create index if not exists outreach_queue_prospect_id_idx
  on outreach_queue (prospect_id);

create index if not exists outreach_queue_created_at_idx
  on outreach_queue (created_at desc);

comment on table outreach_queue is
  'AI-generated outreach messages ready for sending. Created by the AI Outreach Agent.';


-- ---------------------------------------------------------------------------
-- copy_suggestions
-- Hero copy suggestions for landing pages and homepage, generated by the SEO Agent.
-- status: pending → approved | rejected | deployed
-- ---------------------------------------------------------------------------
create table if not exists copy_suggestions (
  id                uuid primary key default gen_random_uuid(),
  created_at        timestamptz not null default now(),
  page              text not null,
  hero_headline     text,
  hero_subheadline  text,
  cta_text          text,
  status            text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'deployed'))
);

create index if not exists copy_suggestions_page_idx
  on copy_suggestions (page);

create index if not exists copy_suggestions_status_idx
  on copy_suggestions (status);

comment on table copy_suggestions is
  'AI-generated hero copy suggestions for key pages. Created by the AI SEO Expert.';
